// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Use to verify MCP connectivity to the STAF Transport app.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/analyze-plan.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var analyze_plan_default = defineTool2({
  name: "analyze_plan",
  title: "Analyze warehouse plan image",
  description: "Extract store numbers, trav\xE9es and zones (Zone 1 / D\xE9bord / Craft) from a photo of a STAF Transport warehouse plan. Provide the image as a data URL (data:image/...;base64,...) or a public https URL.",
  inputSchema: {
    imageUrl: z2.string().min(10).describe("Image as a data URL (data:image/png;base64,...) or a public https:// URL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ imageUrl }) => {
    const supabaseUrl = process.env.SUPABASE_URL;
    const anonKey = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!supabaseUrl || !anonKey) {
      return {
        content: [{ type: "text", text: "Backend not configured." }],
        isError: true
      };
    }
    try {
      const res = await fetch(`${supabaseUrl}/functions/v1/analyze-plan`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${anonKey}`,
          apikey: anonKey
        },
        body: JSON.stringify({ image: imageUrl })
      });
      const text = await res.text();
      if (!res.ok) {
        return {
          content: [{ type: "text", text: `analyze-plan failed (${res.status}): ${text}` }],
          isError: true
        };
      }
      let parsed;
      try {
        parsed = JSON.parse(text);
      } catch {
        parsed = text;
      }
      return {
        content: [{ type: "text", text: typeof parsed === "string" ? parsed : JSON.stringify(parsed) }],
        structuredContent: typeof parsed === "object" && parsed !== null ? parsed : void 0
      };
    } catch (err) {
      return {
        content: [{ type: "text", text: `Error: ${err instanceof Error ? err.message : String(err)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "staf-transport-mcp",
  title: "STAF Transport MCP",
  version: "0.1.0",
  instructions: "Tools for the STAF Transport dispatch app. Use `echo` to verify connectivity. Use `analyze_plan` to extract store numbers, trav\xE9es and zones from a photo of a warehouse plan.",
  tools: [echo_default, analyze_plan_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
